---
domain_name:                "yggdrasil.local"
fqdn:                       "{{ hostname }}.{{ domain_name }}"

internal_host:              "{{ fqdn }}"

gateway:                    "192.168.1.1"
domain_name_servers:
- "127.0.0.1"
- "192.168.1.1"

timezone:                   "Europe/Paris"

# users and passwords should be defined in a vault or a plain text file or just here as follow:
#####################################
# work_users:
# - name:           'fanarie'
#   password:       'password'
#
# root_password:    'password'
#
# password_salt:    'my_password_salt'
# 
# foundry_password: 'foundry'
#
# pfx_password:     'p455w0rd'
# 
# external_host:    'my.external.domain'
#####################################
# You can generate a salt with the following shell command:
# cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w ${1:-32} | head -n 1

foundry:
  version:                  "9.269"
  ports:
    local:                  30000
    internal:               31337
    external:               31337
  
certificates:
  authority:
    name:                   "{{ domain_name }}"
    common_name:            "Yggdrasil Certificate Authority"
    state:                  "MIDGARD"
    organization:           "YGGDRASIL"
    organizational_unit:    "YGGDRASIL.LOCAL"
  
  server:
    common_name:            "{{ internal_host }}"
    subject_atl_names:
    - "DNS:*.{{ domain_name }}"
    - "DNS:{{ external_host }}"
  
  clients:
  - "gwenola"
  - "kensan"
  - "neldorin"
  - "bill"
  - "glim"
  
caddy_hosts:
- host:                     "{{ internal_host }}:{{ foundry.ports.internal }}"
  reverse_proxy:            "localhost:{{  foundry.ports.local }}"
  ssl:
    crt:                    "{{ certificates.server.name    | default(certificates.server.common_name)    }}.crt"
    key:                    "{{ certificates.server.name    | default(certificates.server.common_name)    }}.key"
    cacert:                 "{{ certificates.authority.name | default(certificates.authority.common_name) }}.crt"
  
- host:                     "{{ external_host }}:{{ foundry.ports.external }}"
  reverse_proxy:            "localhost:{{ foundry.ports.local }}"
  ssl:
    crt:                    "{{ certificates.server.name    | default(certificates.server.common_name)    }}.crt"
    key:                    "{{ certificates.server.name    | default(certificates.server.common_name)    }}.key"
    cacert:                 "{{ certificates.authority.name | default(certificates.authority.common_name) }}.crt"
    client_certs:           "{{ certificates.clients        | product( [ '.crt' ] ) | map('join') | list  }}" 
  
