---
domain_name: "yggdrasil.local"
fqdn: "{{ hostname }}.{{ domain_name }}"
internal_host: "{{ fqdn }}"
external_hosts:
  - "iy1sixwy.fbxos.fr"

autostart: true

foundry:
  version: "12.331"
  port: 30000 

homebrewery:
  version: "3.14.2"
  port: 8000
  mongodb:
    port: 27017

caddy:
  port: 1337

  certificates:
    authority:
        name: "{{ domain_name }}"
        common_name: "Yggdrasil Certificate Authority"
        state: "MIDGARD"
        organization: "YGGDRASIL"
        organizational_unit: "YGGDRASIL.LOCAL"

    server:
        common_name: "{{ internal_host }}"
        subject_atl_names: "{{ ( [ 'DNS:*.' + domain_name ] ) + ( [ 'DNS:' ] | product( external_hosts | default([]) )\
                          \ | map('join') | list ) }}"

    clients:
      - "phaelyn"
      - "visiteur"
