---
- name: Add keyring for nodejs
  ansible.builtin.apt_key:
    url: "{{ node_repo_signature }}"
    keyring: "/etc/apt/trusted.gpg.d/{{ node_repo_signature_gpg }}"
  become: true

- name: Create sources list file for nodejs
  ansible.builtin.apt_repository:
    filename: "nodejs"
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/{{ node_repo_signature_gpg }}] {{ node_repo }} {{ node_distribution_release\
         \ }} {{ node_distribution_source }}"
  become: true

- name: Install nodejs
  ansible.builtin.apt:
    name: "nodejs"
    state: present
    update_cache: true
    autoremove: true
    force_apt_get: true
  become: true
