---
- name: restart foundry-vtt
  service: 
    name:   "foundry-vtt_v{{ ( foundry.versions | first ).split('.')[0] }}.service"
    state:  "restarted"
  when:
    - foundryvtt_start    is not changed
    - foundry.autostart   | default(true)
  become:   true

- name: restart caddy
  service: 
    name:   "caddy.service"
    state:  "restarted"
  when:
    - caddy_start         is not changed
    - foundry.autostart   | default(true)
  become:   true
