---
- name: Add keyring for caddy
  ansible.builtin.apt_key:
    url: "https://dl.cloudsmith.io/public/caddy/stable/gpg.key"
    keyring: "/etc/apt/trusted.gpg.d/caddy-stable-keyring.gpg"
  become: true

- name: Create sources list file for caddy
  ansible.builtin.copy:
    content: |
      deb     [signed-by=/etc/apt/trusted.gpg.d/caddy-stable-keyring.gpg] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main
      deb-src [signed-by=/etc/apt/trusted.gpg.d/caddy-stable-keyring.gpg] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main
    dest: "/etc/apt/sources.list.d/caddy-stable.list"
    owner: "root"
    group: "root"
    mode: "0644"
  become: true

- name: Install caddy
  ansible.builtin.apt:
    name: "caddy"
    state: present
    update_cache: true
    autoremove: true
    force_apt_get: true
  become: true
