---
- name: add keyring for nodejs
  apt_key:
    url:            "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    keyring:        "/etc/apt/trusted.gpg.d/nodesource-keyring.gpg"
  become:           true

- name: create sources list file for nodejs
  copy:
    content:        |
      deb     [signed-by=/etc/apt/trusted.gpg.d/nodesource-keyring.gpg] https://deb.nodesource.com/{{ node_repo }} {{ ansible_distribution_release }} main
      deb-src [signed-by=/etc/apt/trusted.gpg.d/nodesource-keyring.gpg] https://deb.nodesource.com/{{ node_repo }} {{ ansible_distribution_release }} main
    dest:           "/etc/apt/sources.list.d/nodesource.list"
    owner:          "root"
    group:          "root"
    mode:           "0644"
  become:           true
  
- name: Install nodejs
  apt: 
    name:           "nodejs"
    state:          present
    update_cache:   yes
    autoremove:     yes
    force_apt_get:  yes
  become:           true
  